SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO AS II
JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.ITEM_ID
# PARENT -> CHILD UPGRADE
WHERE II.ITEM_ID NOT IN (
    SELECT PA.ITEM_ID
    FROM ITEM_TREE CH
    JOIN ITEM_TREE PA ON PA.ITEM_ID = CH.PARENT_ITEM_ID
)
ORDER BY 1 DESC
;