-- 코드를 작성해주세요
SELECT PA.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE AS PA
LEFT JOIN ITEM_TREE AS CH ON PA.ITEM_ID = CH.PARENT_ITEM_ID
JOIN ITEM_INFO AS I ON PA.ITEM_ID = I.ITEM_ID
WHERE CH.ITEM_ID IS NULL
ORDER BY PA.ITEM_ID DESC
;