-- 코드를 입력하세요
SELECT *
FROM
(
    SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(
        C.DAILY_FEE * (1 - D.DISCOUNT_RATE / 100) * 30
    ) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D ON C.CAR_TYPE = D.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND D.DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID # 11/1~11/30 대여 불가
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        # NOT(이전 = END < 기간 시작 OR 이후 = START > 기간 끝)
        WHERE END_DATE >= '2022-11-01'
        AND START_DATE <= '2022-11-30'
    )
    GROUP BY C.CAR_ID, C.CAR_TYPE    
) AS T
WHERE FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
;