-- 코드를 입력하세요
SELECT 
    YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT O.USER_ID) / (
        SELECT COUNT(*)
        FROM USER_INFO
        WHERE JOINED >= '2021-01-01' AND JOINED < '2022-01-01'
    ), 1) AS PUCHASED_RATIO
FROM USER_INFO AS U
JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID
WHERE U.JOINED >= '2021-01-01' AND U.JOINED < '2022-01-01'
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR, MONTH
;