-- 코드를 작성해주세요
WITH RECURSIVE T AS(
	# non-recursive (첫번째 루프에서만 실행)
	SELECT ID, PARENT_ID, 1 AS GENERATION # 초기값
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
	UNION ALL
    
	# recursive
	# 실행 때마다 행의 위치 기억해서 다음행 읽어옴
	SELECT CH.ID, CH.PARENT_ID, PA.GENERATION + 1 AS GENERATION
	FROM ECOLI_DATA AS CH
    JOIN T AS PA ON CH.PARENT_ID = PA.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM T
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY 2
;