-- 코드를 입력하세요
WITH T AS(
    SELECT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)

SELECT H.CAR_ID, IFNULL(T.AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
LEFT JOIN T ON H.CAR_ID = T.CAR_ID
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC
;