WITH T AS(
    SELECT CAR_ID # 대여중
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16'
    AND END_DATE >= '2022-10-16'
)

SELECT
    C.CAR_ID,
    (
        CASE
        WHEN T.CAR_ID IS NOT NULL THEN '대여중'
        ELSE '대여 가능'
        END
    ) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
LEFT JOIN T ON C.CAR_ID = T.CAR_ID
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC
;