SELECT F.FLAVOR
FROM 
(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS SO
    FROM FIRST_HALF
    GROUP BY FLAVOR
) AS F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS SO
    FROM JULY
    GROUP BY FLAVOR
) AS J ON F.FLAVOR = J.FLAVOR
ORDER BY F.SO + J.SO DESC
LIMIT 3
;