WITH RECURSIVE T AS(
    SELECT 0 AS H
    UNION ALL
    SELECT H + 1
    FROM T
    WHERE H < 23
)
SELECT T.H AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS AO
RIGHT JOIN T ON HOUR(AO.DATETIME) = T.H
GROUP BY T.H
ORDER BY 1
;