-- 코드를 입력하세요
WITH RECURSIVE T AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM T
    WHERE HOUR < 23
)

SELECT T.HOUR, COUNT(A.ANIMAL_ID) AS COUNT #COUNT(*)은 NULL도 1만큼 집계, 그 외 집계함수는 NULL은 카운팅 안함
FROM ANIMAL_OUTS AS A
RIGHT JOIN T ON HOUR(A.DATETIME) = T.HOUR
GROUP BY T.HOUR #HOUR(A.DATETIME) 기준으로 하면 0인 결과 집계 안됨
ORDER BY 1
;