-- 코드를 입력하세요
WITH RECURSIVE T AS(
    SELECT 9 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM T
    WHERE HOUR < 19
)

SELECT T.HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS AS A
RIGHT JOIN T ON HOUR(A.DATETIME) = T.HOUR
GROUP BY HOUR(A.DATETIME)
ORDER BY 1
;