-- 코드를 작성해주세요
SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I INNER JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (
    SELECT I2.ITEM_ID
    FROM ITEM_INFO I2
    WHERE I2.RARITY = 'RARE'
)
ORDER BY T.ITEM_ID DESC
;