# PARENT: RARE -> SELECT CHILD INFO
SELECT CHILD.ITEM_ID, CHILD.ITEM_NAME, CHILD.RARITY
FROM ITEM_INFO AS PARENT
JOIN ITEM_TREE AS IT ON PARENT.ITEM_ID = IT.PARENT_ITEM_ID
JOIN ITEM_INFO AS CHILD ON IT.ITEM_ID = CHILD.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY 1 DESC
;