-- 코드를 작성해주세요
SELECT CH.ID, CH.GENOTYPE AS GENOTYPE, PA.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA PA LEFT JOIN ECOLI_DATA CH
ON PA.ID = CH.PARENT_ID
WHERE CH.GENOTYPE & PA.GENOTYPE = PA.GENOTYPE
ORDER BY CH.ID
;