SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (T.MAXS - E.SIZE_OF_COLONY) AS YEAR_DEV,ID
FROM ECOLI_DATA AS E
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXS
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS T ON YEAR(E.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY 1, 2
;