-- 코드를 작성해주세요
SELECT T2.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT AS D
JOIN HR_EMPLOYEES AS E ON D.DEPT_ID = E.DEPT_ID
JOIN (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    HAVING SUM(SCORE) = (
        SELECT MAX(SC)
        FROM (
            SELECT SUM(SCORE) AS SC
            FROM HR_GRADE
            GROUP BY EMP_NO
            ) AS T
    )
) AS T2 ON E.EMP_NO = T2.EMP_NO
;