SELECT COUNT(*) AS FISH_COUNT, MAX(RI.LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM 
(
    SELECT ID, IFNULL(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
) RI INNER JOIN FISH_INFO I
ON RI.ID = I.ID
GROUP BY I.FISH_TYPE
HAVING AVG(RI.LENGTH) >= 33
ORDER BY FISH_TYPE
;